; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?DotProduct@@YAHQAH0HH@Z			; DotProduct
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
;rtc$TMZ	SEGMENT
;__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
;rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
;rtc$IMZ	SEGMENT
;__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
;rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?DotProduct@@YAHQAH0HH@Z
_TEXT	SEGMENT
_i$1 = -32						; size = 4
_j$ = -20						; size = 4
_result$ = -8						; size = 4
_x$ = 8							; size = 4
_y$ = 12						; size = 4
_xsize$ = 16						; size = 4
_ysize$ = 20						; size = 4
?DotProduct@@YAHQAH0HH@Z PROC				; DotProduct, COMDAT

; Line 2
	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 3
	mov	DWORD PTR _result$[ebp], 0
; Line 4
	mov	DWORD PTR _j$[ebp], 0
; Line 5
	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN3@DotProduct
$LN2@DotProduct:
	mov	eax, DWORD PTR _i$1[ebp]
	add	eax, 1
	mov	DWORD PTR _i$1[ebp], eax
$LN3@DotProduct:
	mov	eax, DWORD PTR _i$1[ebp]
	cmp	eax, DWORD PTR _xsize$[ebp]
	jge	SHORT $LN1@DotProduct
; Line 7
	mov	eax, DWORD PTR _i$1[ebp]
	mov	ecx, DWORD PTR _x$[ebp]
	mov	edx, DWORD PTR _j$[ebp]
	mov	esi, DWORD PTR _y$[ebp]
	mov	eax, DWORD PTR [ecx+eax*4]
	imul	eax, DWORD PTR [esi+edx*4]
	add	eax, DWORD PTR _result$[ebp]
	mov	DWORD PTR _result$[ebp], eax
; Line 8
	mov	eax, DWORD PTR _j$[ebp]
	add	eax, 1
	mov	DWORD PTR _j$[ebp], eax
; Line 9
	jmp	SHORT $LN2@DotProduct
$LN1@DotProduct:
; Line 11
	mov	eax, DWORD PTR _result$[ebp]
; Line 13
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?DotProduct@@YAHQAH0HH@Z ENDP				; DotProduct
_TEXT	ENDS
END
